/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.state.forstrs.cache;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import java.util.function.LongBinaryOperator;

/**
 * LRU cache for ReducingState/AggregatingState accumulators (umbrella spec §2 component 14).
 *
 * <h3>Hit path</h3>
 *
 * <p>{@link #tryFold(byte[], Object)} combines the new input in-place on the operator thread, marks
 * the entry dirty, and returns {@code true}. No engine I/O needed.
 *
 * <h3>Miss path</h3>
 *
 * <p>Caller detects the miss via {@link #tryFold(byte[], Object)} returning {@code false} and routes
 * through {@link PendingMissTable} for convoy coalescing. Once the GET resolves, caller calls
 * {@link #put(byte[], Object)} to populate the cache entry.
 *
 * <h3>Flush</h3>
 *
 * <p>On LRU eviction or barrier flush ({@link #flushAllDirty()}), dirty entries are written back
 * via the {@code flushCallback} supplied at construction time. The callback receives {@code
 * (compositeKey, serializedValue)} and is responsible for enqueuing the PUT.
 *
 * <h3>V1 design notes</h3>
 *
 * <ul>
 *   <li>Keys are {@code byte[]} (composite key generated by {@link
 *       org.apache.flink.state.forstrs.state.ForStRsReducingStateV2}).
 *   <li>Accumulators are typed objects ({@code ACC}) — no per-fold serialization.
 *   <li>LinkedHashMap access-order LRU. Future upgrade: back with {@link
 *       org.apache.flink.state.forstrs.keyed.FlatStateCache} for GC-free operation (requires
 *       serialize/deserialize on fold; traded off for V1 simplicity).
 *   <li>The {@code flushCallback} decouples this class from {@code VectorizedClassifier} / {@code
 *       SlotArenaScope}, enabling standalone unit tests without those heavy dependencies. Full
 *       classifier wiring is performed by {@code ForStRsReducingStateV2} (P11 integration).
 * </ul>
 *
 * @param <IN> the input type supplied by add() callers
 * @param <ACC> the accumulator type (for ReducingState, IN == ACC)
 */
public final class ReducingAggregatingCache<IN, ACC> {

    /** Default maximum number of entries before LRU eviction kicks in. */
    private static final int DEFAULT_MAX_ENTRIES = 64 * 1024;

    private final BiFunction<ACC, IN, ACC> combiner;
    private final BiConsumer<byte[], ACC> flushCallback;
    private final LinkedHashMap<BytesKey, Entry<ACC>> entries;
    private final int maxEntries;

    /**
     * A6-H1: per-key generation counter. Bumped on every {@link #invalidate} so a concurrently
     * in-flight miss-resolve lambda can detect it raced with an {@code onClear} and skip its
     * stale {@code cache.put}. Survives invalidation (the entry's BytesKey is removed but the
     * generation entry stays) so the resolve lambda sees the bumped value even after the slot
     * has been wiped. Pruned lazily on the next successful {@link #putIfGen}.
     *
     * <p>A7-M1: bounded at {@link #maxEntries}. Mutations happen only on the mailbox thread; the
     * async resolve lambda reads via {@link #currentGen} but never mutates. We use an
     * insertion-ordered {@link LinkedHashMap} guarded by {@link #generationsLock} so concurrent
     * reads from the resolve callback see a consistent map state. When the size exceeds
     * {@link #maxEntries} we evict oldest-by-insertion-order generation entries that are NOT
     * currently in the {@link #entries} map — these are stale tombstones from long-ago
     * invalidations whose original resolve callback has either already raced and lost, or will
     * never arrive (the worst-case correctness regression is that an absurdly-long-stalled
     * resolve lambda for an evicted gen sees gen=0 and proceeds to put — same outcome as a
     * normal miss-resolve, so no data-loss). Generation entries whose key is still cached are
     * preserved to keep the race-detection signal live for any in-flight resolves.
     */
    private final LinkedHashMap<BytesKey, Long> generations = new LinkedHashMap<>();

    /** Monitor guarding {@link #generations} for cross-thread reads from miss-resolve callbacks. */
    private final Object generationsLock = new Object();

    /**
     * E8-H1: pending-flush slot for evictions that fire while {@link #generationsLock} is held.
     *
     * <p>The LRU's {@code removeEldestEntry} hook runs inside {@code entries.put} — which we may
     * be calling from inside {@link #putIfGen} under the {@code generationsLock}. Invoking the
     * engine-PUT {@code flushCallback} directly from that hook would dispatch an FFI call (a
     * potentially-blocking mailbox-stalling operation) WHILE the monitor is held. Any
     * cross-thread {@code currentGen} read (e.g. from the async miss-resolve callback) would
     * stall behind the engine PUT for an arbitrary duration.
     *
     * <p>Fix: when {@code removeEldestEntry} fires and the evicted entry is dirty, stash
     * {@code (key, acc)} into this slot instead of flushing. The caller (the lock-holding
     * method) reads + clears the slot after releasing the lock and dispatches the FFI flush
     * then.
     *
     * <p>Single-slot is sufficient because each {@code entries.put} can evict at most one
     * eldest entry (the LinkedHashMap LRU contract). Concurrent access to this field is
     * impossible under the cache's single-mailbox-thread mutation contract: only one
     * mailbox-thread mutator runs at a time, and the async miss-resolve callback only reads
     * {@link #generations} (never {@link #entries}).
     */
    private BytesKey pendingFlushKey;

    private ACC pendingFlushValue;

    /**
     * Cleanup-C3: per-cache reusable view of an externally-owned byte buffer slice. Used by the
     * zero-alloc lookup overloads ({@link #tryFold(byte[], int, int, Object)}, {@link
     * #contains(byte[], int, int)}, {@link #peek(byte[], int, int)}). The state class can pass the
     * shared key buffer (from {@code DataOutputSerializer.getSharedBuffer()}) without producing a
     * fresh {@code byte[]} per add() — eliminating the {@code keyOut.getCopyOfBuffer()} alloc on
     * the cache-hit path described in the audit (B3-H1 / B3-H2).
     *
     * <p>Single-threaded by the cache's contract (per-RecordContext serialization); the field is
     * mutated in place during each lookup and consumed before the call returns.
     */
    private final BytesKey scratch = new BytesKey();

    // -----------------------------------------------------------------
    // Entry
    // -----------------------------------------------------------------

    private static final class Entry<ACC> {
        ACC acc;
        boolean dirty;

        Entry(ACC acc, boolean dirty) {
            this.acc = acc;
            this.dirty = dirty;
        }
    }

    // -----------------------------------------------------------------
    // Construction
    // -----------------------------------------------------------------

    /**
     * Creates a cache with the default capacity ({@value #DEFAULT_MAX_ENTRIES} entries).
     *
     * @param combiner {@code (acc, in) -> acc'} applied on cache hits
     * @param flushCallback invoked on LRU eviction and {@link #flushAllDirty()} with the raw
     *     composite key bytes and the accumulated value; must not throw
     */
    public ReducingAggregatingCache(
            BiFunction<ACC, IN, ACC> combiner, BiConsumer<byte[], ACC> flushCallback) {
        this(combiner, flushCallback, DEFAULT_MAX_ENTRIES);
    }

    /**
     * Creates a cache with an explicit capacity limit.
     *
     * @param combiner {@code (acc, in) -> acc'} applied on cache hits
     * @param flushCallback invoked on LRU eviction and {@link #flushAllDirty()}
     * @param maxEntries maximum number of entries before the LRU eldest is evicted
     */
    public ReducingAggregatingCache(
            BiFunction<ACC, IN, ACC> combiner,
            BiConsumer<byte[], ACC> flushCallback,
            int maxEntries) {
        this.combiner = combiner;
        this.flushCallback = flushCallback;
        this.maxEntries = maxEntries;
        // access-order LRU LinkedHashMap; removeEldestEntry flushes dirty entries on eviction
        this.entries =
                new LinkedHashMap<>(Math.min(maxEntries, 1024), 0.75f, true) {
                    @Override
                    protected boolean removeEldestEntry(Map.Entry<BytesKey, Entry<ACC>> eldest) {
                        if (size() > maxEntries) {
                            Entry<ACC> e = eldest.getValue();
                            if (e.dirty) {
                                // E8-H1: do NOT call flushCallback here — that would dispatch
                                // an engine-PUT FFI call while we may be inside the
                                // generationsLock (putIfGen path). Stash the eldest dirty
                                // entry into the pendingFlush slot; the caller drains it
                                // AFTER releasing the lock.
                                pendingFlushKey = eldest.getKey();
                                pendingFlushValue = e.acc;
                                // Mark clean so a concurrent flushAllDirty (no path today,
                                // but defensive) cannot double-flush the same entry.
                                e.dirty = false;
                            }
                            return true;
                        }
                        return false;
                    }
                };
    }

    // -----------------------------------------------------------------
    // B10-H2 primitive specialization — factory methods
    // -----------------------------------------------------------------

    /**
     * B10-H2: returns a {@code long}-specialized cache that stores its accumulator as a primitive
     * {@code long} field on each entry, eliminating the per-hit {@code Long.valueOf} box that the
     * general cache pays when {@code ACC == Long} (typical for Q12 SumAgg / CountAgg). Callers must
     * supply a {@link LongBinaryOperator} combiner ({@code (long, long) -> long}) and a
     * {@code (byte[], long) -> void} flush callback.
     *
     * <p>This is hybrid option (c) in the B10-H2 audit: well-known caller archetypes (the state
     * class detects {@code valueSerializer instanceof LongSerializer} and unwraps a stock
     * {@code ReduceFunction.reduce(Long, Long)} into a {@link LongBinaryOperator}) route to this
     * specialization; everything else falls back to the general {@code BiFunction}-typed cache via
     * the regular constructor.
     *
     * <p>The flush callback receives a primitive {@code long}, so no {@code Long} box is needed on
     * the eviction / barrier-drain path either. The only box that may still occur is on the input
     * side ({@code Long} → {@code long} unbox in the call site that invokes {@link
     * LongReducingAggregatingCache#tryFold(byte[], long)}), which is dwarfed by the eliminated
     * write-back box on a typical hit-heavy Q12 pattern.
     */
    public static LongReducingAggregatingCache forLong(
            LongBinaryOperator combiner,
            LongReducingAggregatingCache.LongFlushCallback flushCallback) {
        return new LongReducingAggregatingCache(combiner, flushCallback);
    }

    /**
     * Capacity-explicit variant of {@link #forLong(LongBinaryOperator,
     * LongReducingAggregatingCache.LongFlushCallback)}.
     */
    public static LongReducingAggregatingCache forLong(
            LongBinaryOperator combiner,
            LongReducingAggregatingCache.LongFlushCallback flushCallback,
            int maxEntries) {
        return new LongReducingAggregatingCache(combiner, flushCallback, maxEntries);
    }

    // -----------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------

    /**
     * Returns {@code true} if this cache has an entry for {@code compositeKey} (hit).
     *
     * @param compositeKey raw composite key bytes
     */
    public boolean contains(byte[] compositeKey) {
        return contains(compositeKey, 0, compositeKey.length);
    }

    /** Cleanup-C3: zero-alloc slice-view variant of {@link #contains(byte[])}. */
    public boolean contains(byte[] buf, int off, int len) {
        return entries.containsKey(scratch.view(buf, off, len));
    }

    /**
     * Peeks at the current accumulator without marking access order. Returns {@code null} on miss.
     *
     * @param compositeKey raw composite key bytes
     */
    public ACC peek(byte[] compositeKey) {
        return peek(compositeKey, 0, compositeKey.length);
    }

    /** Cleanup-C3: zero-alloc slice-view variant of {@link #peek(byte[])}. */
    public ACC peek(byte[] buf, int off, int len) {
        Entry<ACC> e = entries.get(scratch.view(buf, off, len));
        return e == null ? null : e.acc;
    }

    /**
     * Returns {@code true} if the entry for {@code compositeKey} is dirty (has unflushed combiner
     * output).
     *
     * @param compositeKey raw composite key bytes
     */
    public boolean isDirty(byte[] compositeKey) {
        Entry<ACC> e = entries.get(scratch.view(compositeKey, 0, compositeKey.length));
        return e != null && e.dirty;
    }

    /**
     * Cache-hit fold: combines {@code input} in-place on the operator thread. Updates the LRU
     * access order, marks the entry dirty, and returns {@code true} on hit. Returns {@code false}
     * on miss (caller must go to miss path).
     *
     * <p>B8-H1: tryFold returns a bare {@code boolean} instead of {@code Optional<ACC>} so the
     * per-record cache-hit path on Q12 incurs no Optional wrapper allocation. Callers that need
     * the post-fold accumulator value can read it via {@link #peek(byte[])} after a {@code true}
     * return (all current callers only need the hit/miss signal, so they never re-probe).
     *
     * @param compositeKey raw composite key bytes
     * @param input the value being added
     * @return {@code true} on hit (folded in place), {@code false} on miss
     */
    public boolean tryFold(byte[] compositeKey, IN input) {
        return tryFold(compositeKey, 0, compositeKey.length, input);
    }

    /**
     * Cleanup-C3: zero-alloc lookup overload. Probes the cache using a slice {@code (buf, off,
     * len)} of an externally-owned byte buffer (typically {@code keyOut.getSharedBuffer()} from a
     * {@code DataOutputSerializer}). On hit, folds in place — no allocation. On miss, returns
     * {@code false}; the caller must subsequently snapshot the slice via {@link #put(byte[], Object)}
     * (passing {@code keyOut.getCopyOfBuffer()} — the only allocation on the miss path) to seed
     * the cache.
     *
     * <p>The scratch slice view is reused across calls; the single-threaded contract of this
     * cache (per-RecordContext lock) guarantees no interleaved probe can clobber it.
     *
     * <p>B8-H1: see {@link #tryFold(byte[], Object)} — returns a bare {@code boolean} to avoid
     * per-call {@code Optional.of(...)} allocation on the Q12 hot path.
     */
    public boolean tryFold(byte[] buf, int off, int len, IN input) {
        Entry<ACC> e = entries.get(scratch.view(buf, off, len));
        if (e == null) {
            return false;
        }
        e.acc = combiner.apply(e.acc, input);
        e.dirty = true;
        return true;
    }

    /**
     * Inserts or replaces the accumulator for {@code compositeKey}. Marks the entry dirty so it
     * will be flushed on the next barrier or LRU eviction.
     *
     * <p>Typical use: called by the miss-resolve path after a GET completes.
     *
     * @param compositeKey raw composite key bytes
     * @param acc the new accumulator (may be null to represent an absent/cleared entry)
     */
    public void put(byte[] compositeKey, ACC acc) {
        entries.put(new BytesKey(compositeKey), new Entry<>(acc, true));
        // E8-H1: drain any deferred eviction flush from removeEldestEntry. No lock is held
        // here, so the engine-PUT can run without blocking cross-thread generation reads.
        drainPendingFlush();
    }

    /**
     * Cleanup-C3: slice-view put variant for the miss-resolve path. Snapshots {@code (buf, off,
     * len)} into a freshly-owned {@code byte[]} for stable storage in the LRU. This is the ONLY
     * allocation on the asyncAdd miss path; the hit path remains alloc-free.
     */
    public void put(byte[] buf, int off, int len, ACC acc) {
        byte[] owned = new byte[len];
        System.arraycopy(buf, off, owned, 0, len);
        entries.put(new BytesKey(owned), new Entry<>(acc, true));
        // E8-H1: drain any deferred eviction flush from removeEldestEntry.
        drainPendingFlush();
    }

    /**
     * A6-H1: returns the current generation for {@code compositeKey}. A miss-resolve lambda
     * snapshots this value BEFORE issuing its GET and passes it to {@link #putIfGen}: if the
     * generation has since been bumped (because {@code onClear → invalidate} fired between the
     * GET-issue and GET-resolve), the put is skipped — preventing a stale accumulator from
     * resurrecting the engine-side DELETE.
     *
     * <p>Returns {@code 0L} if no generation entry exists for the key (i.e. the key has never
     * been invalidated in this session). Generation values are strictly monotonic across the
     * cache lifetime.
     */
    public long currentGen(byte[] compositeKey) {
        return currentGen(compositeKey, 0, compositeKey.length);
    }

    /** Zero-alloc slice-view variant of {@link #currentGen(byte[])}. */
    public long currentGen(byte[] buf, int off, int len) {
        // A7-M1: synchronize on generationsLock because reads come from the async
        // miss-resolve callback while writes (invalidate / putIfGen) run on the mailbox
        // thread. We must NOT use the shared {@link #scratch} here — that field is reserved
        // for the mailbox-only zero-alloc lookup paths and would race with concurrent
        // tryFold/peek/contains calls. Allocate a fresh BytesKey view for the cross-thread
        // lookup; this is the only allocation on the gen-check path and is bounded to the
        // miss-resolve callback (cold path).
        synchronized (generationsLock) {
            BytesKey probe = new BytesKey().view(buf, off, len);
            Long g = generations.get(probe);
            return g == null ? 0L : g;
        }
    }

    /**
     * A6-H1: miss-resolve store path. Inserts {@code (compositeKey, acc)} ONLY if the current
     * generation matches {@code expectedGen} — i.e. no {@code invalidate} fired in between the
     * resolve lambda's GET issue and its callback. Returns {@code true} if the put took effect,
     * {@code false} if it was skipped due to a generation mismatch (the lambda must drop the
     * value).
     *
     * <p>This is the race-safe counterpart of {@link #put(byte[], Object)}: callers on the
     * miss-resolve path MUST go through this method rather than the unconditional {@code put}
     * to be A6-H1 correct.
     */
    public boolean putIfGen(byte[] compositeKey, ACC acc, long expectedGen) {
        // A7-M1: hold generationsLock across the gen-check + put so that a concurrent
        // mailbox-thread invalidate cannot slip a generation bump in between. Without this,
        // the gen-check could see expectedGen, invalidate could bump and remove the entry,
        // then we'd resurrect the stale acc into entries despite the bump.
        //
        // E8-H1: the {@code entries.put} below may trigger {@code removeEldestEntry}, which
        // would historically invoke {@code flushCallback} (engine-PUT FFI) DIRECTLY — i.e.
        // a potentially-blocking engine call while {@code generationsLock} is held. Any
        // cross-thread {@link #currentGen} read from the async miss-resolve callback would
        // stall behind that FFI. The {@code removeEldestEntry} override now defers the flush
        // into a {@link #pendingFlushKey}/{@link #pendingFlushValue} slot; we drain it OUTSIDE
        // the synchronized block.
        boolean inserted;
        synchronized (generationsLock) {
            BytesKey probe = new BytesKey().view(compositeKey, 0, compositeKey.length);
            Long g = generations.get(probe);
            long current = g == null ? 0L : g;
            if (current != expectedGen) {
                return false;
            }
            entries.put(new BytesKey(compositeKey), new Entry<>(acc, true));
            // Lazy GC: if a generation slot existed but matched (i.e. the key was invalidated
            // and then re-resolved at the same gen — only possible at gen=0), drop the entry
            // so the map doesn't grow unboundedly across stable steady-state. We only prune
            // when the generation is at the "no invalidation" baseline; non-zero gens stay to
            // preserve the race-detection signal for any other in-flight resolves on the same
            // key.
            if (expectedGen == 0L) {
                generations.remove(probe);
            }
            inserted = true;
        }
        // E8-H1: drain the deferred eviction flush OUTSIDE the lock — the engine PUT may
        // block on the engine's classifier queue, but no other thread can be blocked on
        // generationsLock waiting for us to release.
        drainPendingFlush();
        return inserted;
    }

    /**
     * Flushes all dirty entries via the flush callback. Called on checkpoint barrier (§3 Trace E).
     * Marks entries clean after flushing.
     *
     * <p>A10-H1: drain any in-flight {@link #pendingFlushKey}/{@link #pendingFlushValue} slot FIRST.
     * The slot is populated by {@code removeEldestEntry} when an LRU eviction was deferred (engine-
     * PUT FFI must not run under {@code generationsLock}). If a prior {@code drainPendingFlush}
     * throw re-stashed an entry, {@code drainPendingFlush} placed it back into {@code entries}
     * marked dirty and the {@code entries} iteration would have picked it up — so the re-stash path
     * is covered without this drain. BUT the SUCCESS-but-not-yet-drained path (a deferred eviction
     * captured into the slot that has not been drained by a subsequent {@code put} or
     * {@code putIfGen}) needs us to materialize the slot before iterating. Failing to drain here
     * would leave the captured (key, value) unflushed forever — {@code removeEldestEntry} already
     * removed it from {@code entries}, marked the original Entry clean (defensive line ~196), and
     * stashed it into the slot. The {@code entries} iteration alone cannot see it.
     *
     * <p>Drain ordering: BEFORE iterating {@code entries}. If the drain's callback throws,
     * propagate immediately — the re-stash logic in {@code drainPendingFlush} will have put the
     * entry back into {@code entries} dirty, and the next checkpoint will retry it (consistent with
     * the E9-H2 contract).
     */
    public void flushAllDirty() {
        drainPendingFlush();
        for (Map.Entry<BytesKey, Entry<ACC>> me : entries.entrySet()) {
            Entry<ACC> e = me.getValue();
            if (e.dirty) {
                flushOne(me.getKey().bytes, e);
            }
        }
    }

    /** Returns the current number of cached entries. */
    public int size() {
        return entries.size();
    }

    /** Clears all entries (does NOT flush dirty entries). Use before state clear operations. */
    public void clear() {
        entries.clear();
    }

    /**
     * A5-H2: removes the entry for the given composite key without invoking the flush callback.
     * Called from the state class's {@code onClear()} hook when {@code asyncClear()} is dispatched
     * via the {@link org.apache.flink.state.forstrs.VectorizedClassifier} DELETE path. Without this,
     * a dirty cached accumulator survives the engine-side DELETE and {@link #flushAllDirty()} on
     * the next barrier would write it back, overwriting the DELETE. Returns {@code true} if an
     * entry was removed.
     */
    public boolean invalidate(byte[] compositeKey) {
        return invalidate(compositeKey, 0, compositeKey.length);
    }

    /** Zero-alloc slice-view variant of {@link #invalidate(byte[])}. */
    public boolean invalidate(byte[] buf, int off, int len) {
        // A6-H1: bump the generation BEFORE removing the entry so that any concurrently
        // in-flight miss-resolve lambda (which captured its generation BEFORE issuing the GET)
        // observes the bump on its subsequent putIfGen check and refuses to write the stale
        // accumulator back. The generation snapshot is keyed by an owned BytesKey copy so it
        // survives the entry's removal — the resolve lambda may run after the entries map has
        // been wiped of this slot.
        BytesKey owned = scratch.view(buf, off, len).snapshot();
        synchronized (generationsLock) {
            generations.merge(owned, 1L, Long::sum);
            // A7-M1: bound generations growth. When the map exceeds maxEntries, evict
            // oldest-by-insertion-order tombstones whose key is no longer present in
            // entries — those have no live cache slot to protect; the worst case for an
            // absurdly-stalled resolve lambda whose tombstone got evicted is that
            // currentGen returns 0L and putIfGen proceeds as a normal cache seed (same
            // shape as a clean cache miss — no data loss).
            if (generations.size() > maxEntries) {
                java.util.Iterator<Map.Entry<BytesKey, Long>> it =
                        generations.entrySet().iterator();
                int overflow = generations.size() - maxEntries;
                while (it.hasNext() && overflow > 0) {
                    Map.Entry<BytesKey, Long> me = it.next();
                    if (!entries.containsKey(me.getKey())) {
                        it.remove();
                        overflow--;
                    }
                }
            }
        }
        return entries.remove(scratch.view(buf, off, len)) != null;
    }

    // -----------------------------------------------------------------
    // Internal helpers
    // -----------------------------------------------------------------

    private void flushOne(byte[] keyBytes, Entry<ACC> entry) {
        flushCallback.accept(keyBytes, entry.acc);
        entry.dirty = false;
    }

    /**
     * E8-H1: drain the deferred LRU-eviction flush slot. Called by every public mutator that
     * may have triggered {@code removeEldestEntry} — i.e. all paths that call {@code
     * entries.put}. The deferred flush is dispatched ONLY after the caller has released any
     * lock it holds, so the engine-PUT FFI never runs while the {@link #generationsLock} (or
     * any future cache-internal lock) is held.
     *
     * <p>E9-H2: the captured (k, v) MUST survive a {@code flushCallback} throw. The prior
     * implementation nulled the slot BEFORE the callback ran — if the engine-PUT FFI threw,
     * the dirty entry was already gone from {@code entries} (removed by
     * {@code removeEldestEntry}), the slot was nulled, and the data was lost. The next
     * {@code flushAllDirty} on barrier would silently miss it. Fix: capture under the lock,
     * dispatch outside it, and on throw re-stash the entry into {@code entries} marked
     * dirty so the next {@code flushAllDirty} retries it. The slot is only cleared in the
     * {@code finally} block, AFTER a successful dispatch (or after re-stash on failure).
     */
    private void drainPendingFlush() {
        BytesKey k;
        ACC v;
        synchronized (generationsLock) {
            k = pendingFlushKey;
            if (k == null) {
                return;
            }
            v = pendingFlushValue;
        }
        boolean delivered = false;
        try {
            flushCallback.accept(k.bytes, v);
            delivered = true;
        } finally {
            synchronized (generationsLock) {
                if (!delivered) {
                    // E9-H2: re-stash so the next flushAllDirty retries the engine-PUT.
                    // removeEldestEntry already marked the original Entry clean (defensive,
                    // see line ~196), so we must insert a NEW Entry with dirty=true. Use the
                    // owned-bytes form of put so the LRU slot owns its key independently of
                    // the BytesKey we captured. If the same key has since been re-inserted by
                    // a concurrent putIfGen, do NOT clobber it — its accumulator is fresher.
                    if (!entries.containsKey(k)) {
                        entries.put(new BytesKey(k.bytes), new Entry<>(v, true));
                    }
                }
                // Clear the slot only after we have either delivered or re-stashed. The
                // pendingFlushKey==k guard handles re-entrant flushCallback paths that may
                // have already overwritten the slot with a fresh eviction.
                if (pendingFlushKey == k) {
                    pendingFlushKey = null;
                    pendingFlushValue = null;
                }
            }
        }
    }

    // -----------------------------------------------------------------
    // Content-equality key wrapper for byte[] in LinkedHashMap
    // -----------------------------------------------------------------

    /**
     * Dual-mode byte-slice key. Owns a {@code byte[]} when used as a stored map key (after
     * {@link #put}); reused as a slice view {@code (buf, off, len)} when used as a probe key
     * (zero-alloc lookup paths). Hash and equality are computed over the active range so both
     * modes compare consistently against each other in the HashMap.
     */
    static final class BytesKey {
        byte[] bytes;
        int off;
        int len;

        /** Constructs an empty scratch view; {@link #view(byte[], int, int)} sets the range. */
        BytesKey() {}

        BytesKey(byte[] bytes) {
            this.bytes = bytes;
            this.off = 0;
            this.len = bytes.length;
        }

        /** Reuses this key to view a slice. Returns {@code this} to chain into a lookup call. */
        BytesKey view(byte[] buf, int off, int len) {
            this.bytes = buf;
            this.off = off;
            this.len = len;
            return this;
        }

        /**
         * Snapshots the current slice as an owned {@code byte[]} suitable for a stored map key.
         * The returned BytesKey does not share storage with any external buffer, so it is safe
         * to keep across mutations of the probe scratch.
         */
        BytesKey snapshot() {
            byte[] copy = new byte[len];
            System.arraycopy(bytes, off, copy, 0, len);
            return new BytesKey(copy);
        }

        @Override
        public boolean equals(Object o) {
            if (!(o instanceof BytesKey)) {
                return false;
            }
            BytesKey bk = (BytesKey) o;
            if (len != bk.len) {
                return false;
            }
            // Range-aware byte comparison. java.util.Arrays.equals(byte[], int, int, byte[], int,
            // int) is JIT-intrinsified on JDK 22+ (AVX2/NEON vector compare), so this is no
            // slower than the legacy full-array compare for typical 8-64-byte composite keys.
            return java.util.Arrays.equals(bytes, off, off + len, bk.bytes, bk.off, bk.off + bk.len);
        }

        @Override
        public int hashCode() {
            // Range-aware hashCode: same algorithm as Arrays.hashCode(byte[]) but over the slice.
            // Keeps hashes consistent between view-mode and owned-mode for the same byte content.
            int h = 1;
            int end = off + len;
            for (int i = off; i < end; i++) {
                h = 31 * h + bytes[i];
            }
            return h;
        }
    }
}
