/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.state.forstrs.cache;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;

/**
 * LRU cache for ReducingState/AggregatingState accumulators (umbrella spec §2 component 14).
 *
 * <h3>Hit path</h3>
 *
 * <p>{@link #tryFold(byte[], Object)} combines the new input in-place on the operator thread, marks
 * the entry dirty, and returns the new accumulator. No engine I/O needed.
 *
 * <h3>Miss path</h3>
 *
 * <p>Caller detects the miss via {@link #tryFold(byte[], Object)} returning empty and routes
 * through {@link PendingMissTable} for convoy coalescing. Once the GET resolves, caller calls
 * {@link #put(byte[], Object)} to populate the cache entry.
 *
 * <h3>Flush</h3>
 *
 * <p>On LRU eviction or barrier flush ({@link #flushAllDirty()}), dirty entries are written back
 * via the {@code flushCallback} supplied at construction time. The callback receives {@code
 * (compositeKey, serializedValue)} and is responsible for enqueuing the PUT.
 *
 * <h3>V1 design notes</h3>
 *
 * <ul>
 *   <li>Keys are {@code byte[]} (composite key generated by {@link
 *       org.apache.flink.state.forstrs.state.ForStRsReducingStateV2}).
 *   <li>Accumulators are typed objects ({@code ACC}) — no per-fold serialization.
 *   <li>LinkedHashMap access-order LRU. Future upgrade: back with {@link
 *       org.apache.flink.state.forstrs.keyed.FlatStateCache} for GC-free operation (requires
 *       serialize/deserialize on fold; traded off for V1 simplicity).
 *   <li>The {@code flushCallback} decouples this class from {@code VectorizedClassifier} / {@code
 *       SlotArenaScope}, enabling standalone unit tests without those heavy dependencies. Full
 *       classifier wiring is performed by {@code ForStRsReducingStateV2} (P11 integration).
 * </ul>
 *
 * @param <IN> the input type supplied by add() callers
 * @param <ACC> the accumulator type (for ReducingState, IN == ACC)
 */
public final class ReducingAggregatingCache<IN, ACC> {

    /** Default maximum number of entries before LRU eviction kicks in. */
    private static final int DEFAULT_MAX_ENTRIES = 64 * 1024;

    private final BiFunction<ACC, IN, ACC> combiner;
    private final BiConsumer<byte[], ACC> flushCallback;
    private final LinkedHashMap<BytesKey, Entry<ACC>> entries;

    /**
     * A6-H1: per-key generation counter. Bumped on every {@link #invalidate} so a concurrently
     * in-flight miss-resolve lambda can detect it raced with an {@code onClear} and skip its
     * stale {@code cache.put}. Survives invalidation (the entry's BytesKey is removed but the
     * generation entry stays) so the resolve lambda sees the bumped value even after the slot
     * has been wiped. Pruned lazily on the next successful {@link #putIfGen}.
     *
     * <p>Single-mutator contract: mutations happen only on the mailbox thread; the async resolve
     * lambda reads via {@link #currentGen} but never mutates. The map is therefore only ever
     * concurrently READ (by the resolve lambda) while WRITES (mailbox thread mutations) are
     * serialised — but we still keep this on a {@link java.util.concurrent.ConcurrentHashMap} so
     * the concurrent read is publishable across threads without explicit volatiles.
     */
    private final java.util.concurrent.ConcurrentHashMap<BytesKey, Long> generations =
            new java.util.concurrent.ConcurrentHashMap<>();

    /**
     * Cleanup-C3: per-cache reusable view of an externally-owned byte buffer slice. Used by the
     * zero-alloc lookup overloads ({@link #tryFold(byte[], int, int, Object)}, {@link
     * #contains(byte[], int, int)}, {@link #peek(byte[], int, int)}). The state class can pass the
     * shared key buffer (from {@code DataOutputSerializer.getSharedBuffer()}) without producing a
     * fresh {@code byte[]} per add() — eliminating the {@code keyOut.getCopyOfBuffer()} alloc on
     * the cache-hit path described in the audit (B3-H1 / B3-H2).
     *
     * <p>Single-threaded by the cache's contract (per-RecordContext serialization); the field is
     * mutated in place during each lookup and consumed before the call returns.
     */
    private final BytesKey scratch = new BytesKey();

    // -----------------------------------------------------------------
    // Entry
    // -----------------------------------------------------------------

    private static final class Entry<ACC> {
        ACC acc;
        boolean dirty;

        Entry(ACC acc, boolean dirty) {
            this.acc = acc;
            this.dirty = dirty;
        }
    }

    // -----------------------------------------------------------------
    // Construction
    // -----------------------------------------------------------------

    /**
     * Creates a cache with the default capacity ({@value #DEFAULT_MAX_ENTRIES} entries).
     *
     * @param combiner {@code (acc, in) -> acc'} applied on cache hits
     * @param flushCallback invoked on LRU eviction and {@link #flushAllDirty()} with the raw
     *     composite key bytes and the accumulated value; must not throw
     */
    public ReducingAggregatingCache(
            BiFunction<ACC, IN, ACC> combiner, BiConsumer<byte[], ACC> flushCallback) {
        this(combiner, flushCallback, DEFAULT_MAX_ENTRIES);
    }

    /**
     * Creates a cache with an explicit capacity limit.
     *
     * @param combiner {@code (acc, in) -> acc'} applied on cache hits
     * @param flushCallback invoked on LRU eviction and {@link #flushAllDirty()}
     * @param maxEntries maximum number of entries before the LRU eldest is evicted
     */
    public ReducingAggregatingCache(
            BiFunction<ACC, IN, ACC> combiner,
            BiConsumer<byte[], ACC> flushCallback,
            int maxEntries) {
        this.combiner = combiner;
        this.flushCallback = flushCallback;
        // access-order LRU LinkedHashMap; removeEldestEntry flushes dirty entries on eviction
        this.entries =
                new LinkedHashMap<>(Math.min(maxEntries, 1024), 0.75f, true) {
                    @Override
                    protected boolean removeEldestEntry(Map.Entry<BytesKey, Entry<ACC>> eldest) {
                        if (size() > maxEntries) {
                            Entry<ACC> e = eldest.getValue();
                            if (e.dirty) {
                                flushOne(eldest.getKey().bytes, e);
                            }
                            return true;
                        }
                        return false;
                    }
                };
    }

    // -----------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------

    /**
     * Returns {@code true} if this cache has an entry for {@code compositeKey} (hit).
     *
     * @param compositeKey raw composite key bytes
     */
    public boolean contains(byte[] compositeKey) {
        return contains(compositeKey, 0, compositeKey.length);
    }

    /** Cleanup-C3: zero-alloc slice-view variant of {@link #contains(byte[])}. */
    public boolean contains(byte[] buf, int off, int len) {
        return entries.containsKey(scratch.view(buf, off, len));
    }

    /**
     * Peeks at the current accumulator without marking access order. Returns {@code null} on miss.
     *
     * @param compositeKey raw composite key bytes
     */
    public ACC peek(byte[] compositeKey) {
        return peek(compositeKey, 0, compositeKey.length);
    }

    /** Cleanup-C3: zero-alloc slice-view variant of {@link #peek(byte[])}. */
    public ACC peek(byte[] buf, int off, int len) {
        Entry<ACC> e = entries.get(scratch.view(buf, off, len));
        return e == null ? null : e.acc;
    }

    /**
     * Returns {@code true} if the entry for {@code compositeKey} is dirty (has unflushed combiner
     * output).
     *
     * @param compositeKey raw composite key bytes
     */
    public boolean isDirty(byte[] compositeKey) {
        Entry<ACC> e = entries.get(scratch.view(compositeKey, 0, compositeKey.length));
        return e != null && e.dirty;
    }

    /**
     * Cache-hit fold: combines {@code input} in-place on the operator thread. Updates the LRU
     * access order, marks the entry dirty, and returns the new accumulator wrapped in {@link
     * Optional}. Returns {@link Optional#empty()} on miss (caller must go to miss path).
     *
     * @param compositeKey raw composite key bytes
     * @param input the value being added
     * @return the new accumulator on hit, or empty on miss
     */
    public Optional<ACC> tryFold(byte[] compositeKey, IN input) {
        return tryFold(compositeKey, 0, compositeKey.length, input);
    }

    /**
     * Cleanup-C3: zero-alloc lookup overload. Probes the cache using a slice {@code (buf, off,
     * len)} of an externally-owned byte buffer (typically {@code keyOut.getSharedBuffer()} from a
     * {@code DataOutputSerializer}). On hit, folds in place — no allocation. On miss, returns
     * empty; the caller must subsequently snapshot the slice via {@link #put(byte[], Object)}
     * (passing {@code keyOut.getCopyOfBuffer()} — the only allocation on the miss path) to seed
     * the cache.
     *
     * <p>The scratch slice view is reused across calls; the single-threaded contract of this
     * cache (per-RecordContext lock) guarantees no interleaved probe can clobber it.
     */
    public Optional<ACC> tryFold(byte[] buf, int off, int len, IN input) {
        Entry<ACC> e = entries.get(scratch.view(buf, off, len));
        if (e == null) {
            return Optional.empty();
        }
        e.acc = combiner.apply(e.acc, input);
        e.dirty = true;
        return Optional.of(e.acc);
    }

    /**
     * Inserts or replaces the accumulator for {@code compositeKey}. Marks the entry dirty so it
     * will be flushed on the next barrier or LRU eviction.
     *
     * <p>Typical use: called by the miss-resolve path after a GET completes.
     *
     * @param compositeKey raw composite key bytes
     * @param acc the new accumulator (may be null to represent an absent/cleared entry)
     */
    public void put(byte[] compositeKey, ACC acc) {
        entries.put(new BytesKey(compositeKey), new Entry<>(acc, true));
    }

    /**
     * Cleanup-C3: slice-view put variant for the miss-resolve path. Snapshots {@code (buf, off,
     * len)} into a freshly-owned {@code byte[]} for stable storage in the LRU. This is the ONLY
     * allocation on the asyncAdd miss path; the hit path remains alloc-free.
     */
    public void put(byte[] buf, int off, int len, ACC acc) {
        byte[] owned = new byte[len];
        System.arraycopy(buf, off, owned, 0, len);
        entries.put(new BytesKey(owned), new Entry<>(acc, true));
    }

    /**
     * A6-H1: returns the current generation for {@code compositeKey}. A miss-resolve lambda
     * snapshots this value BEFORE issuing its GET and passes it to {@link #putIfGen}: if the
     * generation has since been bumped (because {@code onClear → invalidate} fired between the
     * GET-issue and GET-resolve), the put is skipped — preventing a stale accumulator from
     * resurrecting the engine-side DELETE.
     *
     * <p>Returns {@code 0L} if no generation entry exists for the key (i.e. the key has never
     * been invalidated in this session). Generation values are strictly monotonic across the
     * cache lifetime.
     */
    public long currentGen(byte[] compositeKey) {
        return currentGen(compositeKey, 0, compositeKey.length);
    }

    /** Zero-alloc slice-view variant of {@link #currentGen(byte[])}. */
    public long currentGen(byte[] buf, int off, int len) {
        Long g = generations.get(scratch.view(buf, off, len));
        return g == null ? 0L : g;
    }

    /**
     * A6-H1: miss-resolve store path. Inserts {@code (compositeKey, acc)} ONLY if the current
     * generation matches {@code expectedGen} — i.e. no {@code invalidate} fired in between the
     * resolve lambda's GET issue and its callback. Returns {@code true} if the put took effect,
     * {@code false} if it was skipped due to a generation mismatch (the lambda must drop the
     * value).
     *
     * <p>This is the race-safe counterpart of {@link #put(byte[], Object)}: callers on the
     * miss-resolve path MUST go through this method rather than the unconditional {@code put}
     * to be A6-H1 correct.
     */
    public boolean putIfGen(byte[] compositeKey, ACC acc, long expectedGen) {
        long current = currentGen(compositeKey);
        if (current != expectedGen) {
            return false;
        }
        entries.put(new BytesKey(compositeKey), new Entry<>(acc, true));
        // Lazy GC: if a generation slot existed but matched (i.e. the key was invalidated and
        // then re-resolved at the same gen — only possible at gen=0), drop the entry so the
        // map doesn't grow unboundedly across stable steady-state. We only prune when the
        // generation is at the "no invalidation" baseline; non-zero gens stay to preserve the
        // race-detection signal for any other in-flight resolves on the same key.
        if (expectedGen == 0L) {
            generations.remove(new BytesKey(compositeKey));
        }
        return true;
    }

    /**
     * Flushes all dirty entries via the flush callback. Called on checkpoint barrier (§3 Trace E).
     * Marks entries clean after flushing.
     */
    public void flushAllDirty() {
        for (Map.Entry<BytesKey, Entry<ACC>> me : entries.entrySet()) {
            Entry<ACC> e = me.getValue();
            if (e.dirty) {
                flushOne(me.getKey().bytes, e);
            }
        }
    }

    /** Returns the current number of cached entries. */
    public int size() {
        return entries.size();
    }

    /** Clears all entries (does NOT flush dirty entries). Use before state clear operations. */
    public void clear() {
        entries.clear();
    }

    /**
     * A5-H2: removes the entry for the given composite key without invoking the flush callback.
     * Called from the state class's {@code onClear()} hook when {@code asyncClear()} is dispatched
     * via the {@link org.apache.flink.state.forstrs.VectorizedClassifier} DELETE path. Without this,
     * a dirty cached accumulator survives the engine-side DELETE and {@link #flushAllDirty()} on
     * the next barrier would write it back, overwriting the DELETE. Returns {@code true} if an
     * entry was removed.
     */
    public boolean invalidate(byte[] compositeKey) {
        return invalidate(compositeKey, 0, compositeKey.length);
    }

    /** Zero-alloc slice-view variant of {@link #invalidate(byte[])}. */
    public boolean invalidate(byte[] buf, int off, int len) {
        // A6-H1: bump the generation BEFORE removing the entry so that any concurrently
        // in-flight miss-resolve lambda (which captured its generation BEFORE issuing the GET)
        // observes the bump on its subsequent putIfGen check and refuses to write the stale
        // accumulator back. The generation snapshot is keyed by an owned BytesKey copy so it
        // survives the entry's removal — the resolve lambda may run after the entries map has
        // been wiped of this slot.
        BytesKey owned = scratch.view(buf, off, len).snapshot();
        generations.merge(owned, 1L, Long::sum);
        return entries.remove(scratch.view(buf, off, len)) != null;
    }

    // -----------------------------------------------------------------
    // Internal helpers
    // -----------------------------------------------------------------

    private void flushOne(byte[] keyBytes, Entry<ACC> entry) {
        flushCallback.accept(keyBytes, entry.acc);
        entry.dirty = false;
    }

    // -----------------------------------------------------------------
    // Content-equality key wrapper for byte[] in LinkedHashMap
    // -----------------------------------------------------------------

    /**
     * Dual-mode byte-slice key. Owns a {@code byte[]} when used as a stored map key (after
     * {@link #put}); reused as a slice view {@code (buf, off, len)} when used as a probe key
     * (zero-alloc lookup paths). Hash and equality are computed over the active range so both
     * modes compare consistently against each other in the HashMap.
     */
    static final class BytesKey {
        byte[] bytes;
        int off;
        int len;

        /** Constructs an empty scratch view; {@link #view(byte[], int, int)} sets the range. */
        BytesKey() {}

        BytesKey(byte[] bytes) {
            this.bytes = bytes;
            this.off = 0;
            this.len = bytes.length;
        }

        /** Reuses this key to view a slice. Returns {@code this} to chain into a lookup call. */
        BytesKey view(byte[] buf, int off, int len) {
            this.bytes = buf;
            this.off = off;
            this.len = len;
            return this;
        }

        /**
         * Snapshots the current slice as an owned {@code byte[]} suitable for a stored map key.
         * The returned BytesKey does not share storage with any external buffer, so it is safe
         * to keep across mutations of the probe scratch.
         */
        BytesKey snapshot() {
            byte[] copy = new byte[len];
            System.arraycopy(bytes, off, copy, 0, len);
            return new BytesKey(copy);
        }

        @Override
        public boolean equals(Object o) {
            if (!(o instanceof BytesKey)) {
                return false;
            }
            BytesKey bk = (BytesKey) o;
            if (len != bk.len) {
                return false;
            }
            // Range-aware byte comparison. java.util.Arrays.equals(byte[], int, int, byte[], int,
            // int) is JIT-intrinsified on JDK 22+ (AVX2/NEON vector compare), so this is no
            // slower than the legacy full-array compare for typical 8-64-byte composite keys.
            return java.util.Arrays.equals(bytes, off, off + len, bk.bytes, bk.off, bk.off + bk.len);
        }

        @Override
        public int hashCode() {
            // Range-aware hashCode: same algorithm as Arrays.hashCode(byte[]) but over the slice.
            // Keeps hashes consistent between view-mode and owned-mode for the same byte content.
            int h = 1;
            int end = off + len;
            for (int i = off; i < end; i++) {
                h = 31 * h + bytes[i];
            }
            return h;
        }
    }
}
